// <auto-generated />
using System;
using AutoCare.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoCare.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251221181345_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoCare.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("date");

                    b.Property<string>("BookingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("BookingTime")
                        .HasColumnType("time");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ConfirmedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ServiceCenterId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("StaffNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingDate")
                        .HasDatabaseName("IDX_Bookings_BookingDate");

                    b.HasIndex("BookingNumber")
                        .IsUnique()
                        .HasDatabaseName("UK_Bookings_BookingNumber");

                    b.HasIndex("ConfirmedBy");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IDX_Bookings_CustomerId");

                    b.HasIndex("ServiceCenterId")
                        .HasDatabaseName("IDX_Bookings_ServiceCenterId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_Bookings_Status");

                    b.HasIndex("VehicleId");

                    b.HasIndex("ServiceCenterId", "BookingDate", "BookingTime")
                        .HasDatabaseName("IDX_Bookings_NoDoubleBooking");

                    b.ToTable("Bookings", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Bookings_CancellationReason", "([Status] = 'Cancelled' AND [CancellationReason] IS NOT NULL) OR ([Status] != 'Cancelled')");

                            t.HasCheckConstraint("CHK_Bookings_Status", "[Status] IN ('Pending', 'Confirmed', 'InProgress', 'Completed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.BookingStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HistoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("IDX_BookingStatusHistory_BookingId");

                    b.HasIndex("ChangedAt")
                        .HasDatabaseName("IDX_BookingStatusHistory_ChangedAt");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("IDX_BookingStatusHistory_ChangedBy");

                    b.ToTable("BookingStatusHistory", null, t =>
                        {
                            t.HasCheckConstraint("CHK_BookingStatusHistory_Status", "[NewStatus] IN ('Pending', 'Confirmed', 'InProgress', 'Completed', 'Cancelled') AND ([OldStatus] IS NULL OR [OldStatus] IN ('Pending', 'Confirmed', 'InProgress', 'Completed', 'Cancelled'))");
                        });
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("NewsletterSubscribed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("City")
                        .HasDatabaseName("IDX_Customers_City");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UK_Customers_UserId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("Technician");

                    b.Property<int>("ServiceCenterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Role")
                        .HasDatabaseName("IDX_Employees_Role");

                    b.HasIndex("ServiceCenterId")
                        .HasDatabaseName("IDX_Employees_ServiceCenterId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UK_Employees_UserId");

                    b.ToTable("Employees", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Employees_HireDate", "[HireDate] <= CAST(GETUTCDATE() AS DATE)");

                            t.HasCheckConstraint("CHK_Employees_Role", "[Role] IN ('Technician', 'Manager', 'Owner')");
                        });
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RefreshTokenId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IDX_RefreshTokens_ExpiresAt")
                        .HasFilter("[IsUsed] = 0 AND [RevokedAt] IS NULL");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IDX_RefreshTokens_Token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IDX_RefreshTokens_UserId");

                    b.ToTable("RefreshTokens", null, t =>
                        {
                            t.HasCheckConstraint("CHK_RefreshTokens_ExpiresAt", "[ExpiresAt] > [CreatedAt]");

                            t.HasCheckConstraint("CHK_RefreshTokens_Revoked", "([RevokedAt] IS NOT NULL AND [IsUsed] = 1) OR ([RevokedAt] IS NULL)");
                        });
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServiceId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("Maintenance");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IDX_Services_IsActive");

                    b.HasIndex("ServiceType")
                        .HasDatabaseName("IDX_Services_ServiceType")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("Services", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Services_BasePrice", "[BasePrice] >= 0");

                            t.HasCheckConstraint("CHK_Services_EstimatedDuration", "[EstimatedDurationMinutes] > 0");

                            t.HasCheckConstraint("CHK_Services_ServiceType", "[ServiceType] IN ('Maintenance', 'SpareParts')");
                        });
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.ServiceCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServiceCenterId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AddressEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("WorkingHours")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("City")
                        .HasDatabaseName("IDX_ServiceCenters_City")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IDX_ServiceCenters_IsActive");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("IDX_ServiceCenters_Location")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("ServiceCenters", null, t =>
                        {
                            t.HasCheckConstraint("CHK_ServiceCenters_Email", "[Email] IS NULL OR [Email] LIKE '%_@__%.__%'");

                            t.HasCheckConstraint("CHK_ServiceCenters_Latitude", "[Latitude] BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CHK_ServiceCenters_Longitude", "[Longitude] BETWEEN -180 AND 180");

                            t.HasCheckConstraint("CHK_ServiceCenters_PhoneNumber", "LEN([PhoneNumber]) >= 10");
                        });
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.ServiceCenterService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServiceCenterServiceId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("CustomPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ServiceCenterId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceCenterId")
                        .HasDatabaseName("IDX_ServiceCenterServices_ServiceCenterId");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("IDX_ServiceCenterServices_ServiceId");

                    b.HasIndex("ServiceCenterId", "ServiceId")
                        .IsUnique()
                        .HasDatabaseName("IDX_ServiceCenterServices_Available")
                        .HasFilter("[IsAvailable] = 1");

                    b.ToTable("ServiceCenterServices", null, t =>
                        {
                            t.HasCheckConstraint("CHK_ServiceCenterServices_CustomPrice", "[CustomPrice] IS NULL OR [CustomPrice] >= 0");
                        });
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UK_Users_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IDX_Users_IsActive");

                    b.HasIndex("UserType")
                        .HasDatabaseName("IDX_Users_UserType");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Users_Email_Format", "[Email] LIKE '%_@__%.__%'");

                            t.HasCheckConstraint("CHK_Users_UserType", "[UserType] IN ('Customer', 'Employee', 'Admin')");
                        });
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VehicleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("VIN")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IDX_Vehicles_CustomerId");

                    b.HasIndex("PlateNumber")
                        .IsUnique()
                        .HasDatabaseName("UK_Vehicles_PlateNumber");

                    b.HasIndex("VIN")
                        .HasDatabaseName("IDX_Vehicles_VIN")
                        .HasFilter("[VIN] IS NOT NULL");

                    b.ToTable("Vehicles", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Vehicles_VIN", "[VIN] IS NULL OR LEN([VIN]) = 17");

                            t.HasCheckConstraint("CHK_Vehicles_Year", "[Year] BETWEEN 1900 AND YEAR(GETUTCDATE()) + 1");
                        });
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.Booking", b =>
                {
                    b.HasOne("AutoCare.Domain.Entities.User", "ConfirmedByUser")
                        .WithMany()
                        .HasForeignKey("ConfirmedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Bookings_ConfirmedBy");

                    b.HasOne("AutoCare.Domain.Entities.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Customers");

                    b.HasOne("AutoCare.Domain.Entities.ServiceCenter", "ServiceCenter")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_ServiceCenters");

                    b.HasOne("AutoCare.Domain.Entities.Service", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Services");

                    b.HasOne("AutoCare.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Vehicles");

                    b.Navigation("ConfirmedByUser");

                    b.Navigation("Customer");

                    b.Navigation("Service");

                    b.Navigation("ServiceCenter");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.BookingStatusHistory", b =>
                {
                    b.HasOne("AutoCare.Domain.Entities.Booking", "Booking")
                        .WithMany("StatusHistory")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookingStatusHistory_Bookings");

                    b.HasOne("AutoCare.Domain.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_BookingStatusHistory_Users");

                    b.Navigation("Booking");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.Customer", b =>
                {
                    b.HasOne("AutoCare.Domain.Entities.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("AutoCare.Domain.Entities.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.Employee", b =>
                {
                    b.HasOne("AutoCare.Domain.Entities.ServiceCenter", "ServiceCenter")
                        .WithMany("Employees")
                        .HasForeignKey("ServiceCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Employees_ServiceCenters");

                    b.HasOne("AutoCare.Domain.Entities.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("AutoCare.Domain.Entities.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Employees_Users");

                    b.Navigation("ServiceCenter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("AutoCare.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.ServiceCenterService", b =>
                {
                    b.HasOne("AutoCare.Domain.Entities.ServiceCenter", "ServiceCenter")
                        .WithMany("ServiceCenterServices")
                        .HasForeignKey("ServiceCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoCare.Domain.Entities.Service", "Service")
                        .WithMany("ServiceCenterServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("ServiceCenter");
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("AutoCare.Domain.Entities.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Vehicles_Customers");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.Booking", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.Service", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ServiceCenterServices");
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.ServiceCenter", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Employees");

                    b.Navigation("ServiceCenterServices");
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.User", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("AutoCare.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
